name: Tests

on:
  push:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/pest.yml'
      - 'composer.lock'
jobs:
  pest:
    name: Run tests
    runs-on: 'ubuntu-20.04'

    env:
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
    steps:
      -   uses: actions/checkout@v2

      -   name: Setup cache environment
          id: extcache
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: '8.0'
            extensions: ${{ env.extensions }}
            key: extensions-${{ hashFiles('composer.lock') }}

      -   name: Cache extensions
          uses: actions/cache@v2
          with:
            path: ${{ steps.extcache.outputs.dir }}
            key: ${{ steps.extcache.outputs.key }}
            restore-keys: ${{ steps.extcache.outputs.key }}

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            extensions: ${{ env.extensions }}
            coverage: none

      -   name: Create database
          run: |
            sudo /etc/init.d/mysql start
            mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -proot mysql
            mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS blog_tests;'

      -   name: Cache composer dependencies
          uses: actions/cache@v2
          with:
            path: vendor
            key: composer-${{ hashFiles('composer.lock') }}

      -   name: Run composer install
          run: composer install -n --prefer-dist

      -   name: Prepare Laravel Application
          run: |
            cp .env.ci .env
            php artisan key:generate

      -   name: Run Pest
          run: vendor/bin/pest
          env:
            DB_PASSWORD: root
